name: 'Rust Cache using sccache'
description: 'Use sccache in your CI for Rust builds'
author: 'MetalBear'
inputs:
  github-token:
    description: 'A GitHub API token to use for calls to the GitHub API with higher rate limits'
    default: ''
  cache-from:
    description: 'The prefix of the cache key to restore from'
    default: 'sccache-'
  cache-to:
    description: 'The cache key to write to'
    default: 'sccache-latest'
branding:
  icon: 'arrow-up'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/post/index.js'
